
version: '3'
dotenv: ['./config/local.yaml']

tasks:
  r:
    cmds:
      - fyne-cross windows -app-id="com.boszhan" -arch=amd64 -name=r ./cmd/retail_app
    silent: true
  w:
    cmds:
      - fyne-cross windows -app-id="com.boszhan" -arch=amd64 -name=w ./cmd/weight_app
    silent: true