
version: '3'
dotenv: ['./config/local.yaml']

tasks:
  build:
    cmds:
      - go build -ldflags -H=windowsgui main.go
    silent: true
  fyne:
    cmds:
      - fyne-cross windows -app-id="com.boszhan" -arch=amd64
    silent: true